### ISSUE TITLE
Remove mp_obj_str_builder and use vstr instead.

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#11]
See: https://github.com/micropython/micropython/commit/05005f679e00241e15a87751d89327f2c4630cb6

**Comment by danicampora** [comment]
and: https://github.com/micropython/micropython/commit/0b9ee86133a2a0524691c6cdac209dbfcb3bf116

**Comment by dpgeorge** [comment]
You should be able to just copy the relevant parts of moduos.c and modusocket.c from the latest stmhal.

**Comment by danicampora** [comment]
Yes, I know, I simply created the ticket in order to not forget about it.

**Comment by danicampora** [comment]
Done
