### ISSUE TITLE
Check usage of vstr when updating with MicroPython's upstream

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#22]
Check this: https://github.com/micropython/micropython/commit/0d3cb6726ddc1bab9fdd11a0aaa259fb436da4b2

**Comment by dpgeorge** [comment]
There might be 1 more change to vstr API today, but after that hopefully it'll be stable :)

**Comment by danicampora** [comment]
Thanks, I'll stay tuned ;)

**Comment by danicampora** [comment]
I think there has been no other vstr API change, is it stable already?

**Comment by danicampora** [comment]
Thanks!
