### ISSUE TITLE
Rename GPIO module to PIN and make it API compatible (as much as possible) with the stmhal port

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#23]

**Comment by dpgeorge** [comment]
Note lower case letters in `Pin`.

**Comment by danicampora** [comment]
Thanks for the remark, I will...

**Comment by danicampora** [comment]
Done with https://github.com/micropython/micropython/commit/53716fcc3effbce1b7cca49d8df30ecaad8bc1dc
