### ISSUE TITLE
Update FatFS to the latest version

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#25]
R0.11 (February 9, 2015)
  Added f_findfirst() and f_findnext(). (_USE_FIND)
  Fixed f_unlink() does not remove cluster chain of the file. (appeared at R0.10c)
  Fixed _FS_NORTC option does not work properly. (appeared at R0.10c)

MicroPython is now using R0.10c

**Comment by dpgeorge** [comment]
There seem to be a lot of (superficial?) changes.  Will need to find some time to merge it properly.

**Comment by danicampora** [comment]
OK, I didn't diff the changes, just saw the release notes and noticed:
 **Fixed f_unlink() does not remove cluster chain of the file**

I have seen that if you try to write a file that is too large to fit in the free space of the drive, the operation fails, you delete the incomplete file, and it seems to be erased, but the space is not really freed, because any subsequent write operations fail because the drive is "still" full.

Anyway, there is no rush. If I find the time before you do, I'll submit a pull request for you to review it.

**Comment by danicampora** [comment]
Already solved.
