### ISSUE TITLE
Add "log in" mechanism when opening a telnet session with the REPL

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#3]
@dpgeorge: This is to discuss if we should add some logging procedure when accessing the REPL over telnet. The way that this currently works is that the pyboard starts the WLAN in AP mode and the network uses WPA2 security, so you already need to know that key to start with. Also there's the point if the netapps (that's the name I am giving now to the telnet and future FTP server) should also work with WLAN in station mode, in that case, having the logging procedure in place will make more sense.

**Comment by dpgeorge** [comment]
Sorry, I don't understand how the logging is supposed to work?  Do you mean "log in" procedure?

**Comment by danicampora** [comment]
Hi, yes, I meant "log in" mechanism, sorry for the typo. It is already done
by the way, I'll close the ticket. When you connect using telnet it greets
you with a welcome message and asks for a user name and password. When you
type the password, no characters are printed, just like in a linux shell.
