### ISSUE TITLE
Move fatfs and file.c, file.h from stmhal to a common folder

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#4]
I am bringing fatfs into the CC3200 port and I just took the latest version from ChaN's website. In the stmhal port a function to find the drives by name was added, but this functionality is already available in the latest version of FatFS. Why not use that version and move it to a common folder? Also the same would apply for "file.c" and "file.h" from the stmhal port. @dpgeorge do you think is a good idea?

**Comment by danicampora** [comment]
@dpgeorge I synchronized my repo with the micropython master a few days ago and I got your latest changes with the common FatFS. I am wrapping up the FTP server (it is functional but needs some polishing), and I think it could be ready to go live, and join the main repo in a couple of days. Please feel free to check the ftp++ branch if you want to take a look at it. Also, wort mentioning that all the code related to Telnet and Ftp can be used with any other micro plus the CC3100 without any additional effort.

**Comment by dpgeorge** [comment]
Looks like you are still using fatfs from within the cc3200 dir, right?  Unfortunately I can't test your code because I don't have a CC3k2 board...

> all the code related to Telnet and Ftp can be used with any other micro plus the CC3100 without any additional effort

Sounds great!  Would be nice to eventually support the CC3100 as a hardware extension module for wifi.

**Comment by danicampora** [comment]
That might be true on the repo, maybe I still have to push a few commits. Sorry about that, I'll push as soon as I get home.

**Comment by danicampora** [comment]
Please take another look at the ftp++ branch, I just pushed. I do have a fatfs folder inside the cc3200 directory, but only for the diskio, ffconf, syscall files.
ff.c and ff.h are taken from the common lib directory.

**Comment by dpgeorge** [comment]
Looks pretty good.  It builds cleanly for me, but I can't test it :)

There are ^M's at the end of each line in mptask.c that you can get rid of.

I think some more files from mods/ can be shared with stmhal; eg pybioctl.h.

**Comment by danicampora** [comment]
True, those ^M's should be removed. I also agree about "pybioctl.h" and some others. I'll take a look.
