### ISSUE TITLE
Disable relative path from FATFS and take care of the current path manually like done by the FTP server

### ISSUE THREAD

**Issue by danicampora** [danicampora/micropython#8]
This might help save on code size.

**Comment by danicampora** [comment]
It only saves around 500 bytes of code... not sure if it's worth the effort...

**Comment by dpgeorge** [comment]
I think it's best to keep relative path.  Lot's of Python stuff relies on it: os.listdir, os.getcwd, os.chdir (of course!), but also imports.  There are other places to save 500 bytes of code if needed.

**Comment by danicampora** [comment]
Yes, that's what I thought. Relative path will stay in. Closing it. Thanks for the input!!
